**NumpyExercise**

In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
z[:]=5
z

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
j = np.arange(9)
j

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
j.reshape(3,3)# when rows*columns = no of element then only it will give us solution

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.array(np.random.random())

array(0.16925438)

In [15]:
np.random.randn(25)

array([ 1.0925947 ,  0.77449606, -0.09132595,  0.12951642,  0.2934155 ,
        0.17472682,  0.46420863, -0.77082595, -0.73884212,  1.54888856,
        0.07396981, -2.0279831 , -0.01495259,  0.73419153,  0.44484681,
       -0.74456486,  0.27643535, -2.06818298,  1.99211857, -0.89226952,
        0.88410347, -1.56162037, -0.49285575, -1.2453441 ,  0.63821078])

In [16]:
np.arange(0.01,1.01,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [17]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [28]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [42]:
mat[3,4]

20

In [50]:
mat[:3,1]

array([ 2,  7, 12])

In [51]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [52]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [53]:
np.sum(mat)

325

In [57]:
mat.var()**0.5

7.211102550927978

In [58]:
mat.std()

7.211102550927978

In [64]:
np.sum(mat,axis=0) # axis = 0 for column 

array([55, 60, 65, 70, 75])

In [65]:
np.sum(mat,axis=1)# axis = 1 for rows 

array([ 15,  40,  65,  90, 115])

In [84]:
j=np.arange(9)
s = j.reshape(3,3)
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
k = np.arange(2,19,2)
print(k)


[ 2  4  6  8 10 12 14 16 18]


In [87]:
z=s+l
z

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [92]:
b = np.random.randint(0,7,5)
b

array([1, 4, 4, 1, 6])

In [95]:
k[b]=k[b]+1

In [96]:
k

array([ 2,  5,  6,  8, 11, 12, 15, 16, 18])

In [121]:
z = np.arange(0,16)
i = z.reshape(2,2,2,2)
i

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [122]:
i.sum(axis=(-1,-2))

array([[ 6, 22],
       [38, 54]])

In [137]:
i[1,1,:,:]#for confiming for element 0,0_0,1_,1,0_1,1

array([[12, 13],
       [14, 15]])

In [183]:
i = np.arange(0,4).reshape(2,2)
i

array([[0, 1],
       [2, 3]])

In [184]:
i[[0,1],:] = i[[1,0],:]

In [185]:
i

array([[2, 3],
       [0, 1]])

In [186]:
a = np.arange(20)

In [187]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [195]:
z = a[0:3].mean()
z

1.0

In [194]:
z

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])